name: Build and Commit index.json (robust scan)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build index.json
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const root = process.cwd();

          function extractPublishedDate(html){
            const m = html.match(/<p>📅\s*([^<]+)<\/p>/i);
            return m ? m[1].trim() : null;
          }

          function extractTitle(html){
            const m = html.match(/<title>([^<]+)<\/title>/i);
            return m ? m[1].trim() : null;
          }

          const posts = [];

          function inspectFolder(folderPath, folderName){
            const indexFile = path.join(folderPath, 'index.html');
            if (fs.existsSync(indexFile)){
              const html = fs.readFileSync(indexFile,'utf8');
              const stats = fs.statSync(indexFile);

              let rel = path.relative(root, indexFile).replace(/\\\\/g,'/');
              if (rel.endsWith('index.html')) rel = rel.replace(/index\.html$/, '');
              // make path absolute from site root
              if (!rel.startsWith('/')) rel = '/' + rel;

              posts.push({
                folder: folderName,
                path: rel,
                title: extractTitle(html) || folderName,
                published_date: extractPublishedDate(html),
                last_modified: stats.mtime.toISOString()
              });
            }
          }

          // Scan Posts/
          const postsDir = path.join(root,'Posts');
          if (fs.existsSync(postsDir)) {
            fs.readdirSync(postsDir, {withFileTypes:true}).forEach(d=>{
              if (d.isDirectory()) inspectFolder(path.join(postsDir,d.name), d.name);
            });
          }

          // Scan top-level folders (skip system and Images)
          fs.readdirSync(root, {withFileTypes:true}).forEach(d=>{
            if (d.isDirectory()) {
              const name = d.name;
              if (['.git','.github','node_modules'].includes(name)) return;
              if (name.toLowerCase() === 'images') return;
              inspectFolder(path.join(root,name), name);
            }
          });

          // Scan Images/
          const images = [];
          ['Images','images'].forEach(dirName=>{
            const imgsDir = path.join(root, dirName);
            if (fs.existsSync(imgsDir)){
              fs.readdirSync(imgsDir, {withFileTypes:true}).forEach(f=>{
                if (f.isFile()){
                  let rel = path.relative(root, path.join(imgsDir,f.name)).replace(/\\\\/g,'/');
                  if (!rel.startsWith('/')) rel = '/' + rel;
                  images.push({ path: rel, name: f.name });
                }
              });
            }
          });

          fs.writeFileSync(path.join(root,'index.json'), JSON.stringify({ posts, images },null,2));
          console.log('Generated index.json with paths:');
          console.log(JSON.stringify({ posts, images },null,2));
          "

      - name: Commit index.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.json
          git diff --quiet || (git commit -m 'Auto-update index.json [skip ci]' && git push)
